hystrix:  
  command:  
      default: 
        execution:  
          isolation:  
            thread:  
              timeoutInMilliseconds: 7000   
feign:
  hystrix: 
    enabled: true
    
    
profile: zhess