#spring.jackson.default-property-inclusion: non_null
mybatis:                               
  mapperLocations: classpath*:META-INF/com/lyl/tcloud/user/provider/mapper/*.xml
  type-aliases-package: com.lyl.tcloud.user.provider.entity
mapper:                
  mappers: 
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  mapper.identity: MYSQL
  
pagehelper:
  helperDialect: mySql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

hystrix:  
  command:  
      default: 
        execution:  
          isolation:  
            thread:  
              timeoutInMilliseconds: 7000   
feign:
  hystrix: 
    enabled: true
    
logging:
  level:
    root: INFO
    com.lyl.tcloud.user.provider.dao: debug
    
profile: bbb